### ISSUE TITLE
Vi-mode indicator

### ISSUE THREAD

**Issue by jsborjesson** [edkolev/promptline.vim#10]
Hi again! Thanks to you my prompt is an inch away from perfect. The only thing I'm missing right now is a way to indicate when you're in Vi-mode (for those of us using `bindkey -v`). Normally this can be done with something like this: 

``` bash
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
```

Maybe it would fit well as a custom slice? Can you perhaps point me in the right direction?

Cheers!

**Comment by biotician** [comment]
Thank you, this was useful! It's working perfectly and seems the right way to do.
