### ISSUE TITLE
Can't use slices functions on zsh

### ISSUE THREAD

**Issue by taromero** [edkolev/promptline.vim#25]
I can't use slices functions to customize the statusline:

`E117: Unknown function: promptline#slices#cwd`

I tried manually sourcing the function before assigning `let g:promptline_preset`:

`source ~/.vim/bundle/promptline.vim/autoload/promptline/slices/cwd.vim`

but I get the same result.

I use Zsh and Tmux.

**Comment by taromero** [comment]
Also, I've installed the plugin using Vundler. Here is the section on my `.vimrc`:

```
Plugin 'edkolev/promptline.vim'
let g:promptline_preset = {
   \'a'    : [ '$USER' ],
   \'b'    : [ promptline#slices#cwd() ],
  \'c'    : [ promptline#slices#vcs_branch() ],
  \'warn' : [ promptline#slices#last_exit_code() ],
  \'z'    : [ promptline#slices#host() ]}
```

**Comment by edkolev** [comment]
This seems like an issue with your plugin manager.

I guess you use Vunlde (not Vundler). If that's the case, you need this `call vundle#end()` before you can use any plugins. Please check docs here https://github.com/gmarik/Vundle.vim and let me know if you still run into issues (but first make sure you're using Vundle correctly).

**Comment by taromero** [comment]
Thanks that did it!
