### ISSUE TITLE
Weird issue with tab completion 

### ISSUE THREAD

**Issue by mhartington** [edkolev/promptline.vim#26]
I'm getting this odd issue with tab completion 
When I try to do any tab completion, I get this odd double text effect with what ever I have in the prompt.

Video of whats happening, this demos the issue better than me trying to explain it.
http://youtu.be/4CUcncXNEic

Here's my prompt for zsh

https://github.com/mhartington/dotfiles/blob/master/prompt

I removed the prompt theme form my shell and tab completion does work as expect.

**Comment by edkolev** [comment]
Oh, that's bizarre :)

However, I can't reproduce this with zsh and your prompt. Could you try to disable some zsh features? Maybe remove these lines https://github.com/mhartington/dotfiles/blob/master/zshrc#L1 https://github.com/mhartington/dotfiles/blob/master/zshrc#L37 and see if any of them is causing the clash. Finally, please try with an empty zshrc.

**Comment by mhartington** [comment]
Seemed to do the trick :+1:  Thanks a lot

**Comment by LeonardKoenig** [comment]
Can you tell me which lines you removed? Sadly the links are dynamic and I doubt removing comments helped the issue ;-)

**Comment by mhartington** [comment]
For my issue, I removed this line `source /Users/mhartington/.iterm2_shell_integration.zsh`, and this `ZLE_RPROMPT_INDENT=0`

**Comment by LeonardKoenig** [comment]
Hm, yep found the lines already (see referenced issue) but I only had the latter line which I did remove.

So I just tried with a clean .zshrc and it won't work either sadly :/

**Comment by bzar** [comment]
Removing ZLE_RPROMPT_INDENT=0 worked for me, but now the right prompt has that annoying one-space indent.

**Comment by jda0** [comment]
I have this issue with bash!
