### ISSUE TITLE
Unmatching arrow?

### ISSUE THREAD

**Issue by yirmiyahu** [edkolev/promptline.vim#62]
<img width="599" alt="screen shot 2017-01-16 at 4 52 25 am" src="https://cloud.githubusercontent.com/assets/7613236/21983813/c8e25d40-dba7-11e6-8c44-c7b5cc391a4e.png">
Any idea why the end of the prompt has that non-matching bright arrow?

**Comment by amcgregor** [comment]
I have a similar issue with intra-section color matching:

<img width="340" alt="screen shot 2017-05-28 at 16 03 43" src="https://cloud.githubusercontent.com/assets/76750/26531805/3f59883e-43bf-11e7-8f39-c033475d870c.png">

**Comment by Tuurlijk** [comment]
Try adjusting the contrast slider in your profile preferences.

Move it further to the left:

![preferences](https://cloud.githubusercontent.com/assets/790979/26546274/7618b16a-4469-11e7-8650-718951370401.png)
