### ISSUE TITLE
If there is '/' contain in git branch name, vcs_branch show incorrect branch name.

### ISSUE THREAD

**Issue by mob5566** [edkolev/promptline.vim#69]
If there is **'/'** contain in git branch name, vcs_branch will show only the parts of brach name after last **'/'**.
I think the root cause is using `branch=${branch##*/}` in `promptline#slices#vcs_branch#function_body`.
Would you fix this condition?

**Comment by tysonclugg** [comment]
According to [the POSIX Shell specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02), `${branch##*/}` will remove the _largest_ prefix pattern matching `*/`.

I'm guessing that removing the _smallest_ prefix pattern would suit your needs better, the pattern for that being `${branch#*/}`.  Have you tried this?  If it works for you, maybe submit a pull request?

**Comment by mob5566** [comment]
Hi @tysonclugg, thank you for your response!

I think the original pattern is correct for the normal condition.
If the result of `git` symbolic-ref --quiet HEAD` is `refs/heads/master`, that works correctly.
But if I have a branch named `test/dev`, that would be `refs/heads/test/dev` and only `dev` was showed.
I think that _slash_ is inappropriate for being a delimiter in the branch name.
Therefore, I decide to close this issue.

Thank you all.
